//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuongDanPhanCongDoAnTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.KetQuas = new HashSet<KetQua>();
            this.KetQuas1 = new HashSet<KetQua>();
        }
    
        public string MSGV { get; set; }
        public string TenGV { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<int> NamBatDau { get; set; }
        public Nullable<double> HSThamNien { get; set; }
        public Nullable<int> HSCM { get; set; }
        public Nullable<int> HSNCKH { get; set; }
    
        public virtual HeSoChuyenMon HeSoChuyenMon { get; set; }
        public virtual NghienCuuKhoaHoc NghienCuuKhoaHoc { get; set; }
        public virtual ThamNienCongTac ThamNienCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQua> KetQuas1 { get; set; }
    }
}
