//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuongDanPhanCongDoAnTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string MSSV { get; set; }
        public string MSGVHD1 { get; set; }
        public string MSGVHD2 { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual GiaoVien GiaoVien1 { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
