//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuongDanPhanCongDoAnTotNghiep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhanCongDoAnEntities : DbContext
    {
        public PhanCongDoAnEntities()
            : base("name=PhanCongDoAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<HeSoChuyenMon> HeSoChuyenMons { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<NghienCuuKhoaHoc> NghienCuuKhoaHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThamNienCongTac> ThamNienCongTacs { get; set; }
    }
}
